### PR TITLE
fix(39): create seeder orchestrator with transactional

### LINKED ISSUE #39: [Bug][Backend]: Gestion de l'ordonnancement du seeding entre les micro-services et persistance de l'état
### Describe the bug

Deux points, le premier est un petite erreur de typo sur la variable qui permet d'attendre que les services dont api est dépendant pour le seeding soient up. 
Le deuxième est de trouver une solution de persistance de l'état du seeding afin de ne plus seulement se baser sur le fait qu'il y ai des users en base pour lancer le seeding ou non. Il faut donc que quand le seeding failed, l'information soit persistée afin qu'au prochain lancement le seeding soit refait même si des users sont renseignés en base. Il faut également prévoir une purge des données dans le cas précis suivant : 
Des utilisateurs sont trouvés en base mais le précédent seeding avait failed, il faut donc le relancer

### Steps to reproduce

Lancement de l'application
Seeding started
Failed du seeding
Relancement de l'application
Seeding skipped --> NOK
Seeding started --> OK

### Expected behavior

Garder la gestion de l'état du seeder côté common pour une implémentation simple dans les différents micro-services, trouver un moyen de persister l'information (fichier stocker dans le volume de chaque service ?)
Et lors du seeding se baser sur le statut de ce fichier

### Stacktrace

_No response_

### Version

develop

### PR DESCRIPTION
**Pull request by Nathan-Pignon**
🚨 **Reminder:** This template is not meant to be submitted as part of the pull request body.  
Please use it as a guide, and replace or remove it before creating your PR.

Thanks again for your work! 💪

# Read Before Submissions

Thank you for your contributions to CoFolio.

When you publish the pull request, please check off relevant items below in the description of your pull request.

---

### Brief description of changes applied

---

### Reference to an Issue, Feature, Task, User Story or another PR

Closes https://github.com/avenirs-esr/avenirs-portfolio-common/issues/39

---

### Documentation

---

### Target Branch

---

### Additional Notes

---

### Known Limitations or Side Effects

---

## ✅ Checklist

Please make sure you have addressed the following before submitting:

- [ ] a11y tested (if the PR includes frontend changes)
- [ ] Tests provided (including unit and integration tests for both frontend and backend)
- [ ] i18n handled (texts are translated)
- [ ] Performance tests
- [ ] No unnecessary code (e.g., debug logs, commented code)
- [ ] Code style and formatting rules respected (linting, conventions, etc.)
- [ ] Semantic Versioning respected
- [ ] Add to `CHANGELOG.md` file all properties and database change and detaiils for the update process

---

# Remember

**DO NOT** keep this template as is when you submit. Please remove or adjust the description when you submit your pull request.

Please do not submit a pull request to ask questions.

Do not submit pull requests without tests that verify or reproduce your intended use case. The pull request will
most likely be automatically closed immediately, unless the change is extremely trivial.

### CODE REVIEW

File: src/main/java/fr/avenirsesr/portfolio/shared/infrastructure/adapter/seeder/SeederRunner.java [hunk 1]
```diff
@@ -1,174 +1,42 @@
...
-  }
+    long userCount = userRepository.countAll();
+    if (userCount > 0) {
+      log.info("{} users found. Seeder skipped.", userCount);
+      return;
+    }
 
-  public void setDependenciesCheck(boolean dependenciesCheck) {
-    this.dependenciesCheck = dependenciesCheck;
+    seederOrchestrator.seedAll(dependenciesCheck, interoperabilityHealthUrl);
```
Comment (BanelhaqB) [inline src/main/java/fr/avenirsesr/portfolio/shared/infrastructure/adapter/seeder/SeederRunner.java]: le `interoperabilityHealthUrl` il n'aurait pas pu être importé directement dans le `seederOrchestrator` j'ai l'impression qu'il n'est pas utilisé ici

**Review by BanelhaqB — COMMENTED** [review]
Un petit commentaire / question sinon c'est good pour moi, merci Nathan

**Review by arnauddeman — APPROVED** [review]
Ok pour moi Nathan,merci.

File: src/main/java/fr/avenirsesr/portfolio/shared/infrastructure/adapter/seeder/SeederRunner.java (hunk 1 above)
Comment (Nathan-Pignon) [reply src/main/java/fr/avenirsesr/portfolio/shared/infrastructure/adapter/seeder/SeederRunner.java]: Oui c'est vrai, c'était dans le cas où plus tard on était amené à faire la dissociation entre le lancement et le seeding mais au final c'est vrai que je vois pas de cas où les valeurs pourraient être différentes, donc je vais modifier, merci 🙂

Comment (BanelhaqB) [reply src/main/java/fr/avenirsesr/portfolio/shared/infrastructure/adapter/seeder/SeederRunner.java]: Merci à toi ;) et puis si un jour ca arrive, on aura qu'a déplacer le `interoperabilityHealthUrl` à ce moment là

**Review by BanelhaqB — APPROVED** [review]
C'est good pour moi, merci Nathan
